# Generated by Django 3.1 on 2020-08-18 10:04

import account.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=150, null=True)),
                ('organization_address', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=150, null=True)),
                ('school_address', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified', models.BooleanField(default=False)),
                ('user_name', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('full_name', models.CharField(max_length=100, null=True)),
                ('birth_date', models.DateTimeField(null=True)),
                ('birth_place', models.CharField(max_length=100, null=True)),
                ('civil_status', models.CharField(max_length=100, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('pylp_batch', models.IntegerField(null=True)),
                ('pylp_year', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1984), account.models.max_value_current_year])),
                ('host_family', models.CharField(max_length=100, null=True)),
                ('present_address', models.CharField(max_length=150, null=True)),
                ('permanent_address', models.CharField(max_length=150, null=True)),
                ('current_work_affiliation', models.CharField(max_length=100, null=True)),
                ('name_address_office_school', models.CharField(max_length=150, null=True)),
                ('ethnicity', models.CharField(max_length=80, null=True)),
                ('religion', models.CharField(max_length=80, null=True)),
                ('facebook_account', models.CharField(max_length=80, null=True)),
                ('contact_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None)),
                ('telephone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None)),
                ('user', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.CreateModel(
            name='MembershipOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inclusive_date', models.DateTimeField(null=True)),
                ('position_held', models.CharField(max_length=150, null=True)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.organization')),
                ('profile', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.profile')),
            ],
            options={
                'verbose_name_plural': 'Membership in Youth Organizations',
            },
        ),
        migrations.CreateModel(
            name='EducationalBackground',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_type', models.CharField(choices=[('E', 'Elementary'), ('H', 'High School'), ('C', 'College'), ('P', 'Post Graduate')], default='C', max_length=1)),
                ('inclusive_date', models.DateTimeField(null=True)),
                ('level_attained', models.CharField(max_length=150, null=True)),
                ('profile', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.profile')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.school')),
            ],
            options={
                'verbose_name_plural': 'Educational Background',
            },
        ),
        migrations.CreateModel(
            name='CommunityActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=150, null=True)),
                ('activity_description', models.CharField(max_length=150, null=True)),
                ('inclusive_date', models.DateTimeField(null=True)),
                ('profile', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.profile')),
                ('sponsor_organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.organization')),
            ],
            options={
                'verbose_name_plural': 'Involvement in Youth/Community Related Activities',
            },
        ),
    ]
