# Generated by Django 3.1 on 2020-08-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateTimeField(null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_place',
            field=models.CharField(max_length=100, null=True, verbose_name='Place of Birth'),
        ),
    ]
