# Generated by Django 3.1 on 2020-08-19 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200819_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityactivity',
            name='inclusive_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='membershiporganization',
            name='inclusive_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(null=True, verbose_name='Date of Birth'),
        ),
    ]
