# Generated by Django 3.1 on 2020-08-19 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20200819_1326'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='committee',
            options={'verbose_name': 'Committee', 'verbose_name_plural': 'Committees'},
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='committee',
            new_name='committees',
        ),
    ]
