# Generated by Django 3.1 on 2020-08-19 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20200819_1338'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='committee',
            options={},
        ),
        migrations.AlterField(
            model_name='profile',
            name='committees',
            field=models.ManyToManyField(blank=True, to='account.Committee'),
        ),
    ]
