# Generated by Django 3.1 on 2020-08-19 06:45

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20200819_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos', verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='contact_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region='PH', verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telephone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region='PH', verbose_name='Telephone Number'),
        ),
    ]
