# Generated by Django 3.1 on 2020-08-19 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20200819_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='electronic_signature',
            field=models.ImageField(blank=True, null=True, upload_to='e_signature', verbose_name='Electronic Signature'),
        ),
    ]
