# Generated by Django 3.1 on 2020-08-19 15:45

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_profile_electronic_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='electronic_signature',
            field=models.ImageField(blank=True, null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='e_signature', verbose_name='Electronic Signature'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='photos', verbose_name='Profile Picture'),
        ),
    ]
