# Generated by Django 3.1 on 2020-08-20 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_auto_20200820_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='electronic_signature',
            field=models.ImageField(blank=True, null=True, upload_to='e_signature', verbose_name='Electronic Signature'),
        ),
    ]
