# Generated by Django 3.1 on 2020-08-20 06:08

import account.models
from django.db import migrations, models
import functools
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_auto_20200820_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to=functools.partial(account.models._update_filename, *(), **{'path': 'photos'}), verbose_name='Profile Picture'),
        ),
    ]
