# Generated by Django 3.1 on 2020-08-27 11:33

import account.models
from django.db import migrations, models
import functools
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0029_auto_20200827_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='electronic_signature',
            field=models.ImageField(blank=True, null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to=functools.partial(account.models._update_filename, *(), **{'path': 'e_signature', 'type': 'SIGNATURES'}), validators=[account.models.validate_image_size], verbose_name='Electronic Signature'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to=functools.partial(account.models._update_filename, *(), **{'path': 'photos', 'type': 'PHOTOS'}), validators=[account.models.validate_image_size], verbose_name='Profile Picture'),
        ),
    ]
