# Generated by Django 3.1 on 2020-08-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0030_auto_20200827_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='civil_status',
            field=models.CharField(choices=[('M', 'Married'), ('S', 'Single'), ('D', 'Divorced'), ('W', 'Widowed')], default='S', max_length=100, null=True, verbose_name='Civil Status'),
        ),
    ]
