# Generated by Django 2.1 on 2018-08-10 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_newslist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newslist',
            options={'verbose_name': 'News List Detail', 'verbose_name_plural': 'News List Details'},
        ),
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
