# Generated by Django 2.1 on 2018-09-12 10:34

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20180912_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content',
            field=djrichtextfield.models.RichTextField(),
        ),
    ]
