# Generated by Django 2.1.10 on 2020-08-11 10:59

from django.db import migrations, models
import news.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to=news.models.get_image_path, validators=[news.models.validate_file_size]),
        ),
    ]
