# Generated by Django 2.1.10 on 2020-08-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_auto_20200811_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='caption',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='date_published',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='share_on_facebook',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='news',
            name='tags',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
