# Generated by Django 2.1.10 on 2020-08-11 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_auto_20200811_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='tags',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
