# Generated by Django 2.1.10 on 2020-08-12 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_auto_20200811_2133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='image',
            new_name='banner',
        ),
    ]
