# Generated by Django 3.1 on 2020-08-19 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0019_auto_20200812_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='categories',
            field=models.ManyToManyField(null=True, related_name='articles', to='news.Category'),
        ),
    ]
