# Generated by Django 3.1 on 2020-08-19 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0020_auto_20200819_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='articles', to='news.Category'),
        ),
    ]
