# Generated by Django 2.1 on 2018-08-10 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='subquote',
        ),
    ]
