# Generated by Django 2.1 on 2018-08-10 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_remove_section_subquote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('value', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(default='')),
                ('twitter', models.URLField(default='')),
                ('instagram', models.URLField(default='')),
                ('linkedin', models.URLField(default='')),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(default='', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='header',
            name='video',
            field=models.URLField(default=''),
        ),
    ]
