# Generated by Django 2.1 on 2018-08-10 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20180810_0417'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fact',
            options={'verbose_name': 'Facts and Figures', 'verbose_name_plural': 'Facts and Figures'},
        ),
        migrations.AlterModelOptions(
            name='header',
            options={'verbose_name': 'Header Details', 'verbose_name_plural': 'Header Details'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': 'Section', 'verbose_name_plural': 'Sections'},
        ),
        migrations.AlterModelOptions(
            name='socialmedia',
            options={'verbose_name': 'Social Media Accounts', 'verbose_name_plural': 'Social Media Accounts'},
        ),
    ]
