# Generated by Django 2.1 on 2018-08-10 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20180810_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
