# Generated by Django 2.1 on 2018-09-15 15:16

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_resourcelistdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=content.models.get_image_path),
        ),
    ]
