# Generated by Django 2.1.10 on 2020-08-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_auto_20200811_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='user_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
