# Generated by Django 2.1.10 on 2020-08-11 06:19

from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_auto_20200811_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignUpInstructions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('content', djrichtextfield.models.RichTextField()),
            ],
            options={
                'verbose_name': 'Signing Up Instruction',
                'verbose_name_plural': 'Signing Up Instructions',
            },
        ),
    ]
