# Generated by Django 2.1.10 on 2020-08-11 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0019_signupinstructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupinstructions',
            name='content',
            field=models.TextField(max_length=500),
        ),
    ]
