# Generated by Django 2.1.10 on 2020-08-11 06:24

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0020_auto_20200811_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupinstructions',
            name='content',
            field=djrichtextfield.models.RichTextField(),
        ),
    ]
