# Generated by Django 2.1.10 on 2020-08-12 09:45

import content.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0021_auto_20200811_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=200, upload_to='resources', validators=[content.models.validate_file_size])),
            ],
        ),
        migrations.RemoveField(
            model_name='resource',
            name='file',
        ),
        migrations.AddField(
            model_name='attachment',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Resource'),
        ),
    ]
