# Generated by Django 3.1 on 2020-08-13 07:10

import content.models
from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0022_auto_20200812_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(max_length=200, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='resources', validators=[content.models.validate_file_size]),
        ),
    ]
