# Generated by Django 3.1 on 2020-08-17 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0027_auto_20200817_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalbackground',
            name='education_type',
            field=models.CharField(choices=[('E', 'Elementary'), ('H', 'High School'), ('C', 'College'), ('P', 'Post Graduate')], default='C', max_length=1),
        ),
        migrations.AddField(
            model_name='educationalbackground',
            name='inclusive_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationalbackground',
            name='level_attained',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='educationalbackground',
            name='school_address',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='educationalbackground',
            name='school_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
    ]
