# Generated by Django 3.1 on 2020-08-17 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0028_auto_20200817_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalbackground',
            name='account',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.account'),
        ),
    ]
