# Generated by Django 3.1 on 2020-08-17 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0031_auto_20200817_1904'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=150, null=True)),
                ('organization_address', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=150, null=True)),
                ('school_address', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='educationalbackground',
            name='school_address',
        ),
        migrations.RemoveField(
            model_name='educationalbackground',
            name='school_name',
        ),
        migrations.AddField(
            model_name='educationalbackground',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='content.school'),
        ),
    ]
