# Generated by Django 3.1 on 2020-08-17 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0032_auto_20200817_1919'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inclusive_date', models.DateTimeField(null=True)),
                ('position_held', models.CharField(max_length=150, null=True)),
                ('account', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.account')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='content.organization')),
            ],
        ),
        migrations.CreateModel(
            name='CommunityActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=150, null=True)),
                ('activity_description', models.CharField(max_length=150, null=True)),
                ('inclusive_date', models.DateTimeField(null=True)),
                ('account', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.account')),
                ('sponsor_organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='content.organization')),
            ],
        ),
    ]
