# Generated by Django 3.1 on 2020-08-17 11:59

import content.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0033_communityactivity_membershiporganization'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communityactivity',
            options={'verbose_name_plural': 'Involvement in Youth/Community Related Activities'},
        ),
        migrations.AlterModelOptions(
            name='educationalbackground',
            options={'verbose_name_plural': 'Educational Background'},
        ),
        migrations.AlterModelOptions(
            name='membershiporganization',
            options={'verbose_name_plural': 'Membership in Youth Organizations'},
        ),
        migrations.RemoveField(
            model_name='account',
            name='batch_and_year',
        ),
        migrations.AddField(
            model_name='account',
            name='pylp_batch',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='pylp_year',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1984), content.models.max_value_current_year]),
        ),
    ]
