# Generated by Django 3.1 on 2020-08-18 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0033_communityactivity_membershiporganization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communityactivity',
            name='account',
        ),
        migrations.RemoveField(
            model_name='communityactivity',
            name='sponsor_organization',
        ),
        migrations.RemoveField(
            model_name='educationalbackground',
            name='account',
        ),
        migrations.RemoveField(
            model_name='educationalbackground',
            name='school',
        ),
        migrations.RemoveField(
            model_name='membershiporganization',
            name='account',
        ),
        migrations.RemoveField(
            model_name='membershiporganization',
            name='organization',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='CommunityActivity',
        ),
        migrations.DeleteModel(
            name='EducationalBackground',
        ),
        migrations.DeleteModel(
            name='MembershipOrganization',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
        migrations.DeleteModel(
            name='School',
        ),
    ]
