# Generated by Django 3.1 on 2020-08-19 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0034_auto_20200818_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupinstructions',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
