# Generated by Django 3.1 on 2020-08-27 11:28

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0036_contactusemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='image',
            field=models.ImageField(upload_to='header/', validators=[content.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='resource',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=content.models.get_image_path, validators=[content.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='resourcelistdetail',
            name='image',
            field=models.ImageField(upload_to='resource_header/', validators=[content.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='section',
            name='section_image',
            field=models.ImageField(upload_to='section/', validators=[content.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='section',
            name='subquote_image',
            field=models.ImageField(upload_to='section/', validators=[content.models.validate_image_size]),
        ),
    ]
